version: '3.4'

services:
  object_effects:
    image: object_effects
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.development
    ports:
      - "8080:80"
      - "9464:9464"
    networks:
      - localnet

networks:
  localnet:
    external: true
